name: E2E Functional Tests Template

on: [push, pull_request]

jobs:
  e2e:
    name: e2e-on-ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:

      - name: e2e/checkout-repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


      - name: e2e/setup-node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: e2e/cache-node-modules
        id: cache-node-modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            node_modules
            C:\Users\runneradmin\.electron-gyp
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: e2e/setup-python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.10"

      - name: e2e/install-os-dependencies
        uses: ./.github/actions/install-os-dependencies
        with:
          os: ${{ runner.os }}


      - name: e2e/install-node-dependencies
        run: |
          npm ci
          cd e2e && npm ci
          npx electron-rebuild --platform=${{ env.RUNNER_OS }} -f -w robotjs --module-dir ../




      - name: e2e/run-playright-tests-linux
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1280x960x24 > /dev/null 2>&1 &
          npm run build-test
          cd e2e
          xvfb-run -a npm run run:e2e || true
          npm run send-report
        env:
          SERVER_VERSION: ${{ inputs.MM_SERVER_VERSION }}
          DESKTOP_VERSION: ${{ inputs.DESKTOP_VERSION }}

      - name: e2e/run-playright-tests-macos
        if: runner.os == 'macOS'
        run: |
          sudo spctl --master-disable
          xattr -dr com.apple.quarantine ./node_modules/electron
          npm run build-test
          cd e2e
          npm run run:e2e || true
          npm run send-report
        env:
          SERVER_VERSION: ${{ inputs.MM_SERVER_VERSION }}
          DESKTOP_VERSION: ${{ inputs.DESKTOP_VERSION }}

      - name: e2e/run-playright-tests-windows
        if: runner.os == 'Windows'
        run: |
          npm run build-test
          cd e2e
          npm run run:e2e || true
          npm run send-report
        env:
          SERVER_VERSION: ${{ inputs.MM_SERVER_VERSION }}
          DESKTOP_VERSION: ${{ inputs.DESKTOP_VERSION }}

      - name: Capture Report Link
        run: echo "REPORT_LINK=$(cat e2e/report-link.txt)" >> $GITHUB_ENV

      - name: e2e/analyze-flaky-tests
        id: analyze-flaky-tests
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            process.chdir('./e2e');
            const { analyzeFlakyTests } = require('./utils/analyze-flaky-test.js');
            const { newFailedTests, os } = analyzeFlakyTests();

            switch (os) {
              case 'linux':
                core.setOutput('NEW_FAILURES_LINUX', newFailedTests.length);
                core.setOutput('REPORT_LINK_LINUX', "${{ env.REPORT_LINK}}");
                newFailedTests.length > 0 ? core.setOutput('STATUS_LINUX', 'failure') : core.setOutput('STATUS_LINUX', 'success');
                break;
              case 'darwin':
                core.setOutput('NEW_FAILURES_MACOS', newFailedTests.length);
                core.setOutput('REPORT_LINK_MACOS', "${{ env.REPORT_LINK}}");
                newFailedTests.length > 0 ? core.setOutput('STATUS_MACOS', 'failure') : core.setOutput('STATUS_MACOS', 'success');
                break;
              case 'win32':
                core.setOutput('NEW_FAILURES_WINDOWS', newFailedTests.length);
                core.setOutput('REPORT_LINK_WINDOWS', "${{ env.REPORT_LINK}}");
                newFailedTests.length > 0 ? core.setOutput('STATUS_WINDOWS', 'failure') : core.setOutput('STATUS_WINDOWS', 'success');
                break;
              default:
                throw new Error(`Unsupported OS: ${os}`);
            }

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}
          path: e2e/mochawesome-report
          retention-days: 7
